In [1]:
import numpy as np
import tensorflow as tf

In [3]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(2, input_shape=(2,), activation='sigmoid', kernel_initializer=tf.keras.initializers.Constant(0.1)),
    tf.keras.layers.Dense(1, activation='sigmoid', kernel_initializer=tf.keras.initializers.Constant(0.1))
])

model.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=1.0), loss='mean_squared_error')

In [4]:
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=np.float32)  # Inputs
y = np.array([[0], [1], [1], [0]], dtype=np.float32)  # Outputs

In [5]:
model.fit(X, y, epochs=10, verbose=0)

In [6]:
predictions = model.predict(X)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step


In [7]:
for i in range(len(X)):
    print(f"Input: {X[i]} -> Predicted Output: {predictions[i]}")

Input: [0. 0.] -> Predicted Output: [0.5021983]
Input: [0. 1.] -> Predicted Output: [0.5030506]
Input: [1. 0.] -> Predicted Output: [0.5030506]
Input: [1. 1.] -> Predicted Output: [0.50389886]


In [7]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

input_layer_size = 2
hidden_layer_size = 4 
output_layer_size = 1
learning_rate = 0.05 

weights_input_hidden = np.random.rand(input_layer_size, hidden_layer_size) - 0.5
weights_hidden_output = np.random.rand(hidden_layer_size, output_layer_size) - 0.5

X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [0]])

epochs = 20000  

for epoch in range(epochs):
    for i in range(len(X)):
        input_layer = X[i].reshape(1, -1)
        hidden_layer_input = np.dot(input_layer, weights_input_hidden)
        hidden_layer_output = sigmoid(hidden_layer_input)

        output_layer_input = np.dot(hidden_layer_output, weights_hidden_output)
        predicted_output = sigmoid(output_layer_input)

        error = y[i] - predicted_output

        d_predicted_output = error * sigmoid_derivative(predicted_output)
        
        error_hidden_layer = d_predicted_output.dot(weights_hidden_output.T)
        d_hidden_layer_output = error_hidden_layer * sigmoid_derivative(hidden_layer_output)

        weights_hidden_output += hidden_layer_output.T.dot(d_predicted_output) * learning_rate
        weights_input_hidden += input_layer.T.dot(d_hidden_layer_output) * learning_rate

print("Final weights from input to hidden layer:\n", weights_input_hidden)
print("Final weights from hidden to output layer:\n", weights_hidden_output)

correct_predictions = 0

for i in range(len(X)):
    input_layer = X[i].reshape(1, -1)
    hidden_layer_output = sigmoid(np.dot(input_layer, weights_input_hidden))
    predicted_output = sigmoid(np.dot(hidden_layer_output, weights_hidden_output))
    
    predicted_binary = 1 if predicted_output > 0.5 else 0
    print(f"Input: {X[i]} -> Predicted Output: {predicted_output} -> Binary Output: {predicted_binary}")
    
    if predicted_binary == y[i][0]:
        correct_predictions += 1

accuracy = (correct_predictions / len(X)) * 100
print(f"Final Accuracy: {accuracy}%")


Final weights from input to hidden layer:
 [[ 0.15234044  1.76488097 -5.17655762 -4.74645454]
 [ 1.20725207 -4.39391314 -5.06147137  2.00751929]]
Final weights from hidden to output layer:
 [[-2.96696193]
 [ 4.19063353]
 [-9.70876141]
 [ 4.75087926]]
Input: [0 0] -> Predicted Output: [[0.13387702]] -> Binary Output: 0
Input: [0 1] -> Predicted Output: [[0.86924496]] -> Binary Output: 1
Input: [1 0] -> Predicted Output: [[0.87741323]] -> Binary Output: 1
Input: [1 1] -> Predicted Output: [[0.14298804]] -> Binary Output: 0
Final Accuracy: 100.0%
